### ISSUE TITLE
How do i close the website

### ISSUE THREAD

**Issue by Doncar06** [p2plabsxyz/vscode-dhost#1]
i can start it up but how do i stop it/close it

**Comment by akhileshthite** [comment]
> i can start it up but how do i stop it/close it

Hey, @Doncar06 

v3.2 UPDATE:
Now you can delete/unpin your data!

https://github.com/p2plabsxyz/dscan/releases/tag/v3.2

👉 Chrome web store: https://chrome.google.com/webstore/detail/dscan-decentralized-qr-co/idpfgkgogjjgklefnkjdpghkifbjenap
