### ISSUE TITLE
Make 'Set Dhost Folder' optional

### ISSUE THREAD

**Issue by arky** [p2plabsxyz/vscode-dhost#3]
Please make Dhost set the folder step optional if the VSCode `${fileWorkspaceFolder}` ( the current opened file's workspace folder) is already defined. 

Testcase:
* Open VSCode using a terminal with ' code . ' from a predefined project directory
*  Set Web3 API
*  Edit your site 
*  Publish the site

**Comment by akhileshthite** [comment]
> Please make Dhost set the folder step optional if the VSCode `${fileWorkspaceFolder}` ( the current opened file's workspace folder) is already defined.
> 
> Testcase:
> 
> * Open VSCode using a terminal with ' code . ' from a predefined project directory
> * Set Web3 API
> * Edit your site
> * Publish the site

Hey @arky,

Thanks for raising these issues!

Fixes: [v0.2.2](https://github.com/p2plabsxyz/dhost/releases/tag/v0.2.2)

You can now test the latest version on VS Code.
